# Generated by Django 2.0.2 on 2018-02-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_um', models.CharField(blank=True, default='', max_length=10, verbose_name='Texto Um')),
                ('texto_dois', models.CharField(blank=True, default='', max_length=20, verbose_name='Texto Dois')),
                ('texto_tres', models.CharField(blank=True, default='', max_length=30, verbose_name='Texto Três')),
            ],
        ),
    ]
